return {
  -- disable trouble package for testing
  -- { "rcarriga/nvim-notify", enabled = false },
}

-- local list = {
--   "alpha",
--   "autopairs",
--   "blink-cmp" ,
--   "bmessages",
--   "catppuccin",
--   "conform" ,
--   "copilot",
--   "copilotchat",
--   "disable" ,
--   "gitsigns",
--   "indent_line" ,
--   "lsp-config",
--   "lualine",
--   "neo-tree" ,
--   "nvim-surround",
--   "render-markdown",
--   "searchbox",
--   "snacks" ,
--   "tabout",
--   "telescope",
--   "todo-comments" ,
--   "toggleterm",
--   "treesitter",
--   "ufo",
--   "which-key",
-- }
